### ISSUE TITLE
Missing control and config register defines

### ISSUE THREAD

**Issue by jonathancurrie** [BoschSensortec/BME280_driver#10]
Missing definitions for:

bme280.c:
line 1055 - BME280_CTRL_HUMIDITY_REG_OVERSAMP_HUMIDITY
line 1117 - BME280_CTRL_HUMIDITY_REG_OVERSAMP_HUMIDITY
line 1206 - BME280_CTRL_MEAS_REG_POWER_MODE
line 1246 - BME280_CTRL_MEAS_REG_POWER_MODE
line 1370 - BME280_CONFIG_REG_SPI3_ENABLE
line 1409 - BME280_CONFIG_REG_SPI3_ENABLE

**Comment by FoujanetG** [comment]
Hello,
Why did you close your issue? Did you find defines?
thanks
