### ISSUE TITLE
I got an ERROR in IAR with Version: 3.2.0

### ISSUE THREAD

**Issue by jiekechoo** [BoschSensortec/BME280_driver#21]
Error[Pe028]: expression must have a constant value F:\code\STM32F103BME280 - boss\DRIVER\src\BME280.c 448

int8_t bme280_set_regs(uint8_t *reg_addr, const uint8_t *reg_data, uint8_t len, const struct bme280_dev *dev)
{
uint8_t temp_buff[len * 2];
}

**Comment by jiekechoo** [comment]
![bme280-abnormal](https://user-images.githubusercontent.com/3350211/27631425-07342782-5c2b-11e7-8c3e-1f854a41fdbf.png)
and the pressure is abnormal.

**Comment by BoschSensortec** [comment]
@jiekechoo ,

It seems that your compiler doesn't support dynamic length arrays. We will update this shortly to support cases where only static length arrays are supported.

**Comment by jiekechoo** [comment]
@BoschSensortec 
I found the solution, Allow VLA in IAR, fixed.

And, the pressure indicators seem unstable.

**Comment by GhostRiderLi** [comment]
there there two errors about shift bits in line 853 and 859 of  bme280.c

**Comment by tkrahn108** [comment]
@GhostRiderLi What is the correct bit shifting?

**Comment by muchajan** [comment]
@tkrahn108 I think, according to the documentation, there should be right shift by 4, not the left shift

**Comment by tkrahn108** [comment]
@muchajan That was also my idea but it doesn't solve my issue #22.

**Comment by muchajan** [comment]
@tkrahn108 Did you check the compensation functions? They seems to differ with the code in documentation

**Comment by tkrahn108** [comment]
@muchajan Before I used this API I had written my own driver with the compensation function provided in the data sheet. But I got the same values. Therefore, I think the unconsistency is not due to the compensation function.

**Comment by MMMUTU** [comment]
Hello gentlemen, i have one silly question not even worthy a new thread, what am i supposed to fill in those strings:
dev.read = user_i2c_read;
dev.write = user_i2c_write;
dev.delay_ms = user_delay_ms;
I have i2c bme280 connection with STM32F429ZI. Pins: PA8 is SCL, PC9 is SDA.
Should i fill anything else anywhere?

**Comment by BoschSensortec** [comment]
@MMMUTU ,

We have now added function templates in the README for the user_i2c_read, user_i2c_write and user_delay_ms and describing what each of these functions should do in the latest release.

**Comment by BoschSensortec** [comment]
@GhostRiderLi ,

Thank you for your prompt feedback. Do find your comments fixed in the latest release.

**Comment by BoschSensortec** [comment]
@jiekechoo ,

Error regarding variable length arrays as been fixed by using a fixed length array for the write. Please close the issue if you do not have any issues related to the v3.3.0 of the driver

**Comment by jiekechoo** [comment]
![image](https://user-images.githubusercontent.com/3350211/28490356-a0c74540-6f0a-11e7-9a44-7ba30c64628b.png)

@BoschSensortec ,
I updated to version 3.3.0, the pressure seems OK. Thank you!
