### ISSUE TITLE
Error in parse sensor data

### ISSUE THREAD

**Issue by SLocke-CA** [BoschSensortec/BME280_driver#24]
The function erroneously shifts the xlsb UP by 4, instead of down by 4.  This presents itself as extra noise when the oversampling ratio is increased (ie, x8 or x16 has more noise than x1, because the xlsb is effectively being ORed into the final data word at a higher bit weighting...)

Also, the variable names are used "incorrectly".  This second part doesn't really matter, as the shift is correctly assigned to the correct value in the byte array, however it makes reading the code very confusing.

The assignments of lines 851 through 864 should be:

```
	data_msb = (uint32_t)reg_data[0] << 12;
	data_lsb = (uint32_t)reg_data[1] << 4;
	data_xlsb = (uint32_t)reg_data[2] >> 4;
	uncomp_data->pressure = data_msb | data_lsb | data_xlsb;

	/* Store the parsed register values for temperature data */
	data_msb = (uint32_t)reg_data[3] << 12;
	data_lsb = (uint32_t)reg_data[4] << 4;
	data_xlsb = (uint32_t)reg_data[5] >> 4;
	uncomp_data->temperature = data_msb | data_lsb | data_xlsb;

	/* Store the parsed register values for temperature data */
	data_msb = (uint32_t)reg_data[6] << 8;
	data_lsb = (uint32_t)reg_data[7];
```

**Comment by BoschSensortec** [comment]
@SLocke-CA ,

This issue has been reported in issue #21 It has been fixed in the latest release v3.3.0. 

Thank you for your feedback. Closing this issue.
