### ISSUE TITLE
API no longer supports compensation of raw data

### ISSUE THREAD

**Issue by xioTechnologies** [BoschSensortec/BME280_driver#30]
Please reintroduce the ability for the API to compensate raw data provided by the host application.  It is not acceptable for the API to block the host application each time measurements are read via I2C.  The API should support host applications that read I2C data asynchronously.

**Comment by BoschSensortec** [comment]
@xioTechnologies ,

Find the requested APIs available in release [v3.3.1](https://github.com/BoschSensortec/BME280_driver/releases/tag/bme280_v3.3.1)
