### ISSUE TITLE
Has it ever compiled wit __KERNEL__ = 1 ?

### ISSUE THREAD

**Issue by ihkwadratzeh** [BoschSensortec/BME280_driver#31]
Hi everyone!
Thanks for providing the API for the BME280. 
Lately, I have been wondering about two things:

Q1. Are the `"#ifdef __KERNEL__"` blocks in bme280_defs.h meant for integration in a LINUX kernel driver module?
Q2. (If answer to Q1 is yes): Has it ever compiled with` __KERNEL__ `set to 1?

If have tired it out and came across some problems that I can only explain if teh code never worked before with __KERNEL__ set to 1:

1.  #if (LONG_MAX) > 0x7fffffff will retun an error on macro expansion as `LONG_MAX` expands to `((long)(~0UL>>1))` in the Linux-Kernel and the cast to "long" does not work at that particular moment. (same happens in `#if (INT_MAX) > ... `comparisons below)

2. either `"#if __have_long32" `or `"#if __have_long64"` will be undefined and cause a preprocessor error  (around line 93/103 in V3.3.1)

The fixes for the problems are quite simple, but I have been wondering if it works with the code as is and I have overseen something obvious that makes it work.

Contact me if you are interested in patches, I think we would need to discuss the soultions before committing as the use of macros like UINT16_C(x)  is not completely clear to me.

Best Regards,

Moritz

**Comment by BoschSensortec** [comment]
Hi @ihkwadratzeh ,

It has been fixed in the current release v3.3.2. Thanks for your input.
