### ISSUE TITLE
Possibly improper value returned by integer version of compensate_humidity function

### ISSUE THREAD

**Issue by m-xor** [BoschSensortec/BME280_driver#40]
According to explanation given in #36 function _compensate_humidity_ returns  1000 * % relative humidity. It's inconsistent with data sheet. Comparison to function _bme280_compensate_H_int32_ in data sheet reveals that both functions are practically the same. But according to commentary,  function _bme280_compensate_H_int32_: "Returns humidity in %RH as unsigned 32 bit integer in Q22.10 format (22 integer and 10 fractional bits). Output value of “47445” represents 47445/1024 = 46.333 %RH".  Also pre final test of upper limit in function _compensate_humidity_ tests value of 419430400/4096=102400, not 100000. So, it appears that function returns rather 1024 * % relative humidity.

**Comment by BoschSensortec** [comment]
@m-xor,

Refer to the latest release for the corrections.

**Comment by m-xor** [comment]
Everything is clear now. Thank you
