### ISSUE TITLE
Always Get the same Values 0, 30000, 0

### ISSUE THREAD

**Issue by adanielc** [BoschSensortec/BME280_driver#54]
I'm having troubles to read the values, in this last attempt in the read and write function I'm putting manually all the parameters. Any Thought?

I'm using an Atmel SAM D21 Xplained pro

this is the result in the console
Temperature, Pressure, Humidity
0, 30000, 0

#include <asf.h>
#include <string.h>
#include <stdio.h>
#include <unistd.h>
#include "bme280.h"

// PREPROCESSOR CONSTANTS
#define BAUDRATE 115200
#define SLAVE_ADDRESS 0x77
#define BME_ID 0x60
#define TIMEOUT 1000

// STRUCTURES
struct usart_module uart_instance;
struct i2c_master_module i2c_master_instance;
struct bme280_dev dev;
struct bme280_data comp_data;

// PROTOTYPES
void print_sensor_data(struct bme280_data *comp_data);
void handle_bme280_error(int8_t _rslt);
void uart_setup(void);
void i2c_master_setup(void);
void user_delay_ms(uint32_t period);
int8_t user_i2c_read();
int8_t user_i2c_write();
int8_t stream_sensor_data_normal_mode(struct bme280_dev *dev);

int main (void)
{
	system_init();
	uart_setup();
	i2c_master_setup();
	
	 
	    int8_t rslt = BME280_OK;

	    dev.dev_id = BME280_I2C_ADDR_SEC;
	    dev.intf = BME280_I2C_INTF;
	    dev.read = user_i2c_read;
	    dev.write = user_i2c_write;
	    dev._delay_ms = user_delay_ms;

	     rslt = bme280_init(&dev);
	     handle_bme280_error(rslt);

		 rslt = stream_sensor_data_normal_mode(&dev);
	      handle_bme280_error(rslt);

	while (1) 
	{
		stream_sensor_data_normal_mode(&dev);	
	}
	 
}

// UART SETUP
void uart_setup(void){
	
	struct usart_config uart_configuration;
	
	usart_get_config_defaults(&uart_configuration);
	
	uart_configuration.baudrate = BAUDRATE;
	uart_configuration.mux_setting = EDBG_CDC_SERCOM_MUX_SETTING;
	uart_configuration.pinmux_pad0 = EDBG_CDC_SERCOM_PINMUX_PAD0;
	uart_configuration.pinmux_pad1 = EDBG_CDC_SERCOM_PINMUX_PAD1;

	
	stdio_serial_init(&uart_instance, EDBG_CDC_MODULE, &uart_configuration);
	usart_enable(&uart_instance);
}

// I2C CONFIGURATION:
void i2c_master_setup(void) {
	
	struct i2c_master_config i2c_master_configuration;
	
	/* Configure OVERFLOW callback */
	i2c_master_get_config_defaults(&i2c_master_configuration);
	
	i2c_master_configuration.generator_source = GCLK_GENERATOR_0;
	i2c_master_configuration.baud_rate = I2C_MASTER_BAUD_RATE_100KHZ;
	i2c_master_configuration.buffer_timeout = 10000;
	i2c_master_configuration.pinmux_pad0 = PINMUX_PA08C_SERCOM0_PAD0;
	i2c_master_configuration.pinmux_pad1 = PINMUX_PA09C_SERCOM0_PAD1;
	
	
	
	while(i2c_master_init(&i2c_master_instance, SERCOM0, &i2c_master_configuration) != STATUS_OK);
	i2c_master_enable(&i2c_master_instance);
}

int8_t stream_sensor_data_normal_mode(struct bme280_dev *dev)
{
	int8_t rslt;
	uint8_t settings_sel;
	struct bme280_data comp_data;

	/* Recommended mode of operation: Indoor navigation */
	dev->settings.osr_h = BME280_OVERSAMPLING_1X;
	dev->settings.osr_p = BME280_OVERSAMPLING_16X;
	dev->settings.osr_t = BME280_OVERSAMPLING_2X;
	dev->settings.filter = BME280_FILTER_COEFF_16;
	dev->settings.standby_time = BME280_STANDBY_TIME_62_5_MS;

	settings_sel = BME280_OSR_PRESS_SEL;
	settings_sel |= BME280_OSR_TEMP_SEL;
	settings_sel |= BME280_OSR_HUM_SEL;
	settings_sel |= BME280_STANDBY_SEL;
	settings_sel |= BME280_FILTER_SEL;
	rslt = bme280_set_sensor_settings(settings_sel, dev);
	rslt = bme280_set_sensor_mode(BME280_NORMAL_MODE, dev);

	printf("Temperature, Pressure, Humidity\r\n");
	/* Delay while the sensor completes a measurement */
	dev->_delay_ms(70);
	rslt = bme280_get_sensor_data(BME280_ALL, &comp_data, dev);
	
	print_sensor_data(&comp_data);
	
	return rslt;
}

void print_sensor_data(struct bme280_data *comp_data)
{
	printf("%ld, %ld, %ld\r\n",comp_data->temperature, comp_data->pressure, comp_data->humidity);
}

void handle_bme280_error(int8_t _rslt)
{
	if (_rslt < BME280_OK) {
		printf("BME280 Error code: %d", _rslt);
		for(;;); /* Trap if error */
		} else if (_rslt > BME280_OK) {
			
		printf("BME280 Warning code: %d", _rslt);
	}
}

void user_delay_ms(uint32_t period)
{
	delay_ms(period);
}

int8_t user_i2c_read()
{
uint8_t read_buffer;
int8_t rslt = 0; /* Return 0 for Success, non-zero for failure */
int16_t timeout = 0;

/* Initialize i2c packet. */
struct i2c_master_packet packet = {
	.address     = SLAVE_ADDRESS,
	.data        = &read_buffer,
	.data_length = 3,
	.ten_bit_address = false,
	.high_speed      = false,
	.hs_master_code  = 0x0,
};

// Send packet:
/* Write buffer to slave until success. SEND REGISTER WE WANT TO READ */
while (i2c_master_write_packet_wait(&i2c_master_instance, &packet) != STATUS_OK) {
	if (timeout++ == TIMEOUT) {	return false; }	// Abort if timeout
}
return rslt;
	
}

int8_t user_i2c_write()
{
  int8_t rslt = 0; /* Return 0 for Success, non-zero for failure */
	int16_t timeout = 0;
	
	/* Initialize i2c packet. */
	struct i2c_master_packet packet = {
		.address     = SLAVE_ADDRESS,
		.data        = 0xFA,
		.data_length = 1,
		.ten_bit_address = false,
		.high_speed      = false,
		.hs_master_code  = 0x0,
	};
	
	// Send packet:
	/* Write buffer to slave until success. SEND REGISTER WE WANT TO READ */
	while (i2c_master_write_packet_wait_no_stop(&i2c_master_instance, &packet) != STATUS_OK) {
		if (timeout++ == TIMEOUT) {	return false; }	// Abort if timeout
	}
	
    return rslt;
}

**Comment by BoschSensortec** [comment]
Closing duplicate issue
