### ISSUE TITLE
consistency

### ISSUE THREAD

**Issue by accabog** [BoschSensortec/BME280_driver#6]
Hi. Just noticed that for the BME280 driver, the registers are defined with the READ bit set, therefore init is always success but writes are not being done. At the same time for BMG160, registers are defined without the READ bit set. BMG160 driver makes more sense to me since you have to SET the read bit in the spi read routine instead of UNSET the bit in the write routine. Maybe it would be a good ideea to have consistency over your drivers. Thanks!

**Comment by BoschSensortec** [comment]
Thanks for the input.
Register definition in the API is following the data sheet. The bit mask for SPI read should be handled in the platform side. 
Please refer the BME280_SPI_bus_read in bme280_support.c file.
