### ISSUE TITLE
Linux SPI sample - setting CS low/high

### ISSUE THREAD

**Issue by schill25** [BoschSensortec/BME280_driver#63]
Hi,
How to I drive the CS line to Low/High from Linux user space. Can you please provide sample. The arduino code uses api's of arduino. In case of linux , we usually access GPIO from /sys/class/gpio.
can you please help in this and also help elaborate the comments that is mentioned as below in the user_spi_write / read operation.
  /*
     * The parameter dev_id can be used as a variable to select which Chip Select pin has
     * to be set low to activate the relevant device on the SPI bus
     */

**Comment by ma-harvey** [comment]
Driving the GPIOs are very much hardware dependent. On some Linux SBCs, such as the raspberry PI, there are special drivers that allow for automatic control of the CS pin for SPI communication.

**Comment by schill25** [comment]
Thank you!
