### ISSUE TITLE
BME280 Humidity: will not go below 52.9%

### ISSUE THREAD

**Issue by k1mgy** [BoschSensortec/BME280_driver#66]
Using the latest BME280 C driver code.  Works well within Atmel Studio (target AT SAM G55) with simple mod for delay_ms to prevent linker conflict.

Tried both floating point and integer versions, with same result: Compensated humidity does not get below approx. 52%.  Blowing on the sensor I can get it up to >90%.

What information may I provide to help debug this?

Note that I am pausing a full 1 Second between Set Mode and Get Data.  I also implemented a check of the Ready bit to prevent clobbering the device:

bool BME280GetStatusBit(const struct bme280_dev *dev)
{
	uint8_t reg_addr = BME280_STATUS;
	uint8_t nStatusByte;
	int8_t rslt = bme280_get_regs(reg_addr, &nStatusByte, 1, dev);
	nStatusByte=nStatusByte>>3;
	return(nStatusByte==0);
}

**Comment by ma-harvey** [comment]
Could it simply be that humidity is 52% at your location ?

In any case, you can heat up the sensor up to 85C, that will surely drop the humidity by a lot.

**Comment by k1mgy** [comment]
Two independent humidity sensors tell me that the room is at 35%.  As the instrument to which the sensor is fitted enters many different environments, and they all read about the same, this is a concern.

I did heat the sensor to about 50C and saw the humidity drop to around 30%.  

Is there a way to independently verify the math involved in compensation?  I can get the raw data and the compensation registers as inputs...

**Comment by ma-harvey** [comment]
We have a spreadsheet that allows us to calculate offline the compensated values from the compensation registers manually (basically verify the integration of the algorithm in the MCU). Because our firewall is a bit restrictive, we are not able to attach it here...

..But another kind user did it for me some time ago 👍 

https://github.com/BoschSensortec/BME280_driver/issues/49#issuecomment-407082708

**Comment by k1mgy** [comment]
Thank you ma-harvey for the spreadsheet link.  I will give it a go and post here my findings.

**Comment by k1mgy** [comment]
Attached is spreadsheet with data gathered by my system.  Accordingly, the spreadsheet humidity result 49766 matches what my system is calculating.

I'll look back at my other measurement tools to see why the difference.

Thank you.  Closing this for now.
[BME280 Results 19 nov 2018.xlsx](https://github.com/BoschSensortec/BME280_driver/files/2596334/BME280.Results.19.nov.2018.xlsx)
