### ISSUE TITLE
Missing function bme280_compensate_H_int32

### ISSUE THREAD

**Issue by jonathancurrie** [BoschSensortec/BME280_driver#9]
Used at line 241 in the support source file.

**Comment by taunusflieger** [comment]
Just remove the "_H_" from the function name. Unfortunatly there are other issues with the code - all sorts of const which are not declared: BME280_TWO_U8X,BME280_ONE_U8X. I don't get the impression that this code has been compiled correctly prior to uploading it ....

**Comment by BoschSensortec** [comment]
We will fix this in the next release.

**Comment by brethash** [comment]
@BoschSensortec was this issue ever resolved?

**Comment by BoschSensortec** [comment]
@brethash,

Please use the following API instead 
`u32 bme280_compensate_humidity_int32(s32 v_uncomp_humidity_s32);`

**Comment by BoschSensortec** [comment]
Fixed in version 3.x
